apps/quizzes/urls.py
from django.urls import path

from .views import (
    quiz,
    quiz_item,
    quiz_result,
    details_stricted,
)


app_name = "quizzes"

urlpatterns = [
    # Quiz views
    # Since quiz's slugs have 4 random characters followed
    # by dash, there won't be any overlap with this urls
    path("list/", quiz.list_view, name="list"),
    path("create/", quiz.create_view, name="create"),
    path("<slug:slug>/", quiz.detail_view, name="detail"),
    path("<slug:slug>/edit/", quiz.edit_view, name="edit"),
    path("<slug:slug>/delete/", quiz.delete_view, name="delete"),
    # QuizItem views
    path(
        "<slug:slug>/item/create/",
        quiz_item.create_view,
        name="item_create",
    ),
    path(
        "<slug:slug>/item/<int:index>/",
        quiz_item.edit_view,
        name="item_edit",
    ),
    path(
        "<slug:slug>/item/<int:index>/delete/",
        quiz_item.delete_view,
        name="item_delete",
    ),
    # QuizResult views
    path(
        "<slug:slug>/results/",
        quiz_result.edit_view,
        name="results_edit",
    ),
    # Details stricted views
    path(
        "<slug:slug>/item/<int:index>/stricted/",
        details_stricted.quiz_item_view,
        name="stricted_item",
    ),
    path(
        "<slug:slug>/results/stricted/",
        details_stricted.quiz_results_view,
        name="stricted_results",
    ),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views import defaults


if not settings.DEBUG:
    from django_otp.admin import OTPAdminSite

    admin.site.__class__ = OTPAdminSite


# Disable unused urls from 3rd party libraries
disabled_urls = [
    path(
        "email/",
        defaults.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    path(
        "inactive/",
        defaults.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
]

urlpatterns = disabled_urls + [
    # Django
    path("admin/", admin.site.urls),
    # 3rd-party
    path("", include("allauth.urls")),
    # Local
    path("", include("apps.pages.urls", namespace="pages")),
    path("", include("apps.users.urls", namespace="users")),
    path("quizzes/", include("apps.quizzes.urls", namespace="quizzes")),
    path("", include("apps.takes.urls", namespace="takes")),
    path("review/", include("apps.reviews.urls", namespace="reviews")),
    path("api/v1/", include("apps.api.urls", namespace="api")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            defaults.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            defaults.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            defaults.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", defaults.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/quizzes/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response

from apps.quizzes import models
from . import serializers


class QuizApiView(APIView):
    def get(self, request):
        quizzes = models.Quiz.objects.filter(status=models.Quiz.Status.APPROVED)
        serializer = serializers.QuizSerializer(quizzes, many=True)
        return Response(serializer.data)

apps/quizzes/views/details_stricted.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models, forms


@login_required
def quiz_item_view(request, slug, index):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not (request.user == quiz.author or request.user.is_staff):
        raise PermissionDenied

    quiz_item = get_object_or_404(
        models.QuizItem.objects.all(),
        quiz__slug=slug,
        index=index,
    )

    quiz_item_answers = quiz_item.answers.all()

    context = {
        "quiz": quiz,
        "quiz_item": quiz_item,
        "quiz_item_answers": quiz_item_answers,
    }

    return TemplateResponse(request, "quizzes/details_stricted/item.html", context)


@login_required
def quiz_results_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not (request.user == quiz.author or request.user.is_staff):
        raise PermissionDenied

    quiz_results = models.QuizResult.objects.filter(quiz=quiz).order_by("score")

    context = {
        "quiz": quiz,
        "quiz_max_score": quiz.items.count(),
        "quiz_results": quiz_results,
    }

    return TemplateResponse(request, "quizzes/details_stricted/results.html", context)

apps/quizzes/views/quiz.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models, forms, filters


@login_required
def list_view(request):
    quizzes = (
        models.Quiz.objects.filter(author=request.user)
        .order_by("-created")
        .prefetch_related("items")
        .annotate(completions=Count("completed_quizzes"))
        .annotate(ititle=Lower("title"))
    )

    # Sorting

    current_sort_field = request.GET.get("sort_by")

    if current_sort_field:
        quizzes = quizzes.order_by(current_sort_field)

    # Filtering

    quizzes = filters.QuizListFilter(request.GET, quizzes)

    filter_form = quizzes.form

    # Paginating

    paginator = Paginator(quizzes.qs, 9)

    page = request.GET.get("page")

    try:
        quizzes = paginator.page(page)
    except PageNotAnInteger:
        quizzes = paginator.page(1)
    except EmptyPage:
        quizzes = paginator.page(paginator.num_pages)

    context = {
        "quizzes": quizzes,
        "filter_form": filter_form,
        "current_sort_field": current_sort_field,
    }

    return TemplateResponse(request, "quizzes/quiz/list.html", context)


@login_required
def create_view(request):

    if request.POST:
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("quizzes:detail", slug=instance.slug)
    else:
        form = forms.QuizForm()

    context = {
        "form": form,
    }

    return TemplateResponse(request, "quizzes/quiz/create.html", context)


@login_required
def detail_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    quiz_items = quiz.items.order_by("index")

    context = {
        "quiz": quiz,
        "quiz_items": quiz_items,
    }

    return TemplateResponse(request, "quizzes/quiz/detail.html", context)


@login_required
def edit_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if quiz.status not in (models.Quiz.Status.DRAFT, models.Quiz.Status.REJECTED):
        raise PermissionDenied

    if request.POST:
        form = forms.QuizForm(request.POST, instance=quiz)

        if form.is_valid():
            instance = form.save()
            return redirect("quizzes:detail", slug=instance.slug)
    else:
        form = forms.QuizForm(instance=quiz)

    context = {"quiz": quiz, "form": form}

    return TemplateResponse(request, "quizzes/quiz/edit.html", context)


@login_required
def delete_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if request.POST:
        form = forms.QuizDeleteForm(request.POST, instance=quiz)

        if form.is_valid():
            quiz.delete()
            return redirect("quizzes:list")
    else:
        form = forms.QuizDeleteForm(instance=quiz)

    context = {"quiz": quiz, "form": form}

    return TemplateResponse(request, "quizzes/quiz/delete.html", context)

apps/quizzes/views/quiz_item.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models, forms


@login_required
def create_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if quiz.status not in (models.Quiz.Status.DRAFT, models.Quiz.Status.REJECTED):
        raise PermissionDenied

    if quiz.items.count() > quiz.MAX_ITEMS_COUNT:
        raise PermissionDenied

    # Initializing empty QuizItem
    quiz_item = models.QuizItem()

    # Creating formset for QuizItemAnswer
    QuizItemAnswerFormset = inlineformset_factory(
        models.QuizItem,
        models.QuizItemAnswer,
        # In this class happens all validation
        formset=forms.QuizItemAnswerFormSet,
        fields=(
            "text",
            "correct",
        ),
        labels={"text": "Answer"},
        extra=0,
        min_num=models.QuizItem.MIN_ANSWERS,
        max_num=models.QuizItem.MAX_ANSWERS,
    )

    if request.POST:
        # Loading form and formset with POST data
        # We actually need to put POST in formset here
        # in case QuizItem form validation fails,
        # otherwise we would have lost formset data
        quiz_item_form = forms.QuizItemForm(request.POST, quiz=quiz)
        quiz_item_answer_formset = QuizItemAnswerFormset(
            request.POST, instance=quiz_item
        )

        if quiz_item_form.is_valid():
            # Saving QuizItem and assigning some data
            quiz_item = quiz_item_form.save(commit=False)
            quiz_item.index = quiz.get_available_item_index()
            quiz_item.quiz = quiz

            # Reinitializing QuizItemAnswer formset so it
            # can use newly created QuizItem instead of
            # empty one we created initially
            quiz_item_answer_formset = QuizItemAnswerFormset(
                request.POST, instance=quiz_item
            )

            if quiz_item_answer_formset.is_valid():
                # Saving everything we have
                quiz_item.save()
                quiz_item_answer_formset.save()
                return redirect("quizzes:detail", slug=quiz.slug)
    else:
        # Initializing basically empty form and formset
        quiz_item_form = forms.QuizItemForm(quiz=quiz)
        quiz_item_answer_formset = QuizItemAnswerFormset(instance=quiz_item)

    context = {
        "quiz": quiz,
        "quiz_item_form": quiz_item_form,
        "quiz_item_answer_formset": quiz_item_answer_formset,
    }

    return TemplateResponse(request, "quizzes/item/create.html", context)


@login_required
def edit_view(request, slug, index):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if quiz.status not in (models.Quiz.Status.DRAFT, models.Quiz.Status.REJECTED):
        raise PermissionDenied

    # Getting QuizItem
    quiz_item = get_object_or_404(
        models.QuizItem.objects.all(),
        quiz__slug=slug,
        index=index,
    )

    # Creating formset for QuizItemAnswer
    QuizItemAnswerFormset = inlineformset_factory(
        models.QuizItem,
        models.QuizItemAnswer,
        # In this class happens all validation
        formset=forms.QuizItemAnswerFormSet,
        fields=(
            "text",
            "correct",
        ),
        labels={"text": "Answer"},
        extra=0,
        min_num=models.QuizItem.MIN_ANSWERS,
        max_num=models.QuizItem.MAX_ANSWERS,
        can_delete=True,
    )

    if request.POST:
        # Loading form and formset with POST data
        quiz_item_form = forms.QuizItemForm(request.POST, instance=quiz_item, quiz=quiz)
        quiz_item_answer_formset = QuizItemAnswerFormset(
            request.POST, instance=quiz_item
        )

        if quiz_item_form.is_valid():
            # Saving QuizItem
            quiz_item = quiz_item_form.save()

            if quiz_item_answer_formset.is_valid():
                # Saving formset
                quiz_item_answer_formset.save()
                return redirect("quizzes:detail", slug=quiz.slug)
    else:
        # Initializing form and formset with instances
        quiz_item_form = forms.QuizItemForm(instance=quiz_item, quiz=quiz)
        quiz_item_answer_formset = QuizItemAnswerFormset(instance=quiz_item)

    context = {
        "quiz": quiz,
        "quiz_item": quiz_item,
        "quiz_item_form": quiz_item_form,
        "quiz_item_answer_formset": quiz_item_answer_formset,
    }

    return TemplateResponse(request, "quizzes/item/edit.html", context)


@login_required
def delete_view(request, slug, index):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if quiz.status not in (models.Quiz.Status.DRAFT, models.Quiz.Status.REJECTED):
        raise PermissionDenied

    quiz_item = get_object_or_404(
        models.QuizItem.objects.all(),
        quiz__slug=slug,
        index=index,
    )

    if request.POST:
        form = forms.QuizItemDeleteForm(request.POST, instance=quiz_item)

        if form.is_valid():
            quiz_item.delete()
            quiz.update_items_indexes()
            return redirect("quizzes:detail", slug=quiz.slug)
    else:
        form = forms.QuizItemDeleteForm(instance=quiz_item)

    context = {"quiz": quiz, "quiz_item": quiz_item, "form": form}

    return TemplateResponse(request, "quizzes/item/delete.html", context)

apps/quizzes/views/quiz_result.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models, forms


@login_required
def edit_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if quiz.status not in (models.Quiz.Status.DRAFT, models.Quiz.Status.REJECTED):
        raise PermissionDenied

    quiz.update_results()

    QuizResultFormSet = modelformset_factory(
        models.QuizResult,
        fields=("text",),
        labels={"text": "Result"},
        extra=0,
        can_delete=False,
        can_order=False,
    )

    if request.POST:
        quiz_result_formset = QuizResultFormSet(
            request.POST,
            queryset=quiz.results.all(),
        )

        if quiz_result_formset.is_valid():
            quiz_result_formset.save()
            return redirect("quizzes:detail", slug=quiz.slug)
    else:
        quiz_result_formset = QuizResultFormSet(
            queryset=quiz.results.all(),
        )

    context = {
        "quiz": quiz,
        "quiz_result_formset": quiz_result_formset,
        "quiz_max_score": quiz.items.count(),
    }

    return TemplateResponse(request, "quizzes/result/edit.html", context)

templates/quizzes/item/create.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load static %}


{% block title %}Create Item | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-10">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Create Item for {{ quiz.title }}</h2>
        </div>
        <form method="post">{% csrf_token %}
            <!-- Rendering formset errors -->
            {% if quiz_item_answer_formset.non_form_errors %}
                <div class="alert alert-block alert-danger offset-sm-2 col-sm-8">
                    {% for error in quiz_item_answer_formset.non_form_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}

            <!-- Rendering PollItem form -->
            <div class="row">
                <div class="offset-sm-2 col-sm-8">
                    {{ quiz_item_form|crispy }}
                </div>
            </div>

            <!-- Rendering PollItemAnswer formset -->
            {% for form in quiz_item_answer_formset %}
                <div class="row form-container align-items-center">
                    <div class="offset-sm-2 col-sm-6 form-group">
                        {{ form.id }}
                        {{ form.text|as_crispy_field }}
                    </div>
                    <div class="col-sm-2 form-group mt-4">
                        {{ form.correct|as_crispy_field }}
                    </div>
                </div>
            {% endfor %}
            {{ quiz_item_answer_formset.management_form }}

            <div class="d-flex justify-content-center mt-3">
                <button class="btn btn-outline-primary mx-1" type="submit">Create</button>
                <a class="btn btn-outline-secondary mx-1" href="{% url 'quizzes:detail' quiz.slug %}">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block js %}
<script type="text/javascript" src="{% static 'dynamic_formset/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $(".row.form-container").formset({
        prefix: "{{ quiz_item_answer_formset.prefix }}",
        addText: "Add another",
        addCssClass: "btn btn-outline-success offset-sm-2 col-sm-2",
        deleteText: "Remove",
        deleteCssClass: "btn btn-outline-danger col-sm-2",
    });
</script>
{% endblock js %}

templates/quizzes/item/delete.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}


{% block title %}Delete Item | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Delete Item {{ quiz_item.index }} from {{ quiz.title }}</h2>
            <p>Are you sure you want to delete this item?</p>
        </div>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex justify-content-center">
                <button class="btn btn-outline-danger" type="submit">Yes</button>
                <a class="btn btn-outline-secondary ms-2" href="{% url 'quizzes:item_edit' quiz.slug quiz_item.index %}">No way</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/quizzes/item/edit.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load static %}


{% block title %}Edit Item | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-10">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Edit Item {{ quiz_item.index }} from {{ quiz.title }}</h2>
        </div>
        <form method="post">{% csrf_token %}
            <!-- Rendering formset errors -->
            {% if quiz_item_answer_formset.non_form_errors %}
                <div class="alert alert-block alert-danger offset-sm-2 col-sm-8">
                    {% for error in quiz_item_answer_formset.non_form_errors %}
                        {{ error }}
                    {% endfor %}
                </div>
            {% endif %}

            <!-- Rendering PollItem form -->
            <div class="row">
                <div class="offset-sm-2 col-sm-8">
                    {{ quiz_item_form|crispy }}
                </div>
            </div>

            <!-- Rendering PollItemAnswer formset -->
            {% for form in quiz_item_answer_formset %}
                <div class="row form-container align-items-center">
                    <div class="offset-sm-2 col-sm-6 form-group">
                        <!-- Adding DELETE field only if this answer is already in database-->
                        {% if form.instance.pk %}{{ form.DELETE }}{% endif %}
                        {{ form.id }}
                        {{ form.text|as_crispy_field }}
                    </div>
                    <div class="col-sm-2 form-group mt-4">
                        {{ form.correct|as_crispy_field }}
                    </div>
                </div>
            {% endfor %}
            {{ quiz_item_answer_formset.management_form }}

            <div class="d-flex justify-content-center mt-3">
                <button class="btn btn-outline-primary mx-1" type="submit">Save</button>
                <a class="btn btn-outline-danger mx-1" href="{% url 'quizzes:item_delete' quiz.slug quiz_item.index %}">Delete</a>
                <a class="btn btn-outline-secondary mx-1" href="{% url 'quizzes:detail' quiz.slug %}">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

{% block js %}
<script type="text/javascript" src="{% static 'dynamic_formset/jquery.formset.js' %}"></script>
<script type="text/javascript">
    $(".row.form-container").formset({
        prefix: "{{ quiz_item_answer_formset.prefix }}",
        addText: "Add another",
        addCssClass: "btn btn-outline-success offset-sm-2 col-sm-2",
        deleteText: "Remove",
        deleteCssClass: "btn btn-outline-danger col-sm-2",
    });
</script>
{% endblock js %}