apps/quizzes/urls.py
from django.urls import path

from .views import (
    quiz,
    quiz_item,
    quiz_result,
    details_stricted,
)


app_name = "quizzes"

urlpatterns = [
    # Quiz views
    # Since quiz's slugs have 4 random characters followed
    # by dash, there won't be any overlap with this urls
    path("list/", quiz.list_view, name="list"),
    path("create/", quiz.create_view, name="create"),
    path("<slug:slug>/", quiz.detail_view, name="detail"),
    path("<slug:slug>/edit/", quiz.edit_view, name="edit"),
    path("<slug:slug>/delete/", quiz.delete_view, name="delete"),
    # QuizItem views
    path(
        "<slug:slug>/item/create/",
        quiz_item.create_view,
        name="item_create",
    ),
    path(
        "<slug:slug>/item/<int:index>/",
        quiz_item.edit_view,
        name="item_edit",
    ),
    path(
        "<slug:slug>/item/<int:index>/delete/",
        quiz_item.delete_view,
        name="item_delete",
    ),
    # QuizResult views
    path(
        "<slug:slug>/results/",
        quiz_result.edit_view,
        name="results_edit",
    ),
    # Details stricted views
    path(
        "<slug:slug>/item/<int:index>/stricted/",
        details_stricted.quiz_item_view,
        name="stricted_item",
    ),
    path(
        "<slug:slug>/results/stricted/",
        details_stricted.quiz_results_view,
        name="stricted_results",
    ),
]

apps/reviews/urls.py
from django.urls import path

from .views import user, staff


app_name = "reviews"

urlpatterns = [
    # User views
    path("<slug:slug>/submit/", user.quiz_submit_for_review_view, name="submit"),
    path(
        "<slug:slug>/cancel_review/",
        user.quiz_cancel_review_view,
        name="cancel_review",
    ),
    path(
        "<slug:slug>/cancel_approve/",
        user.quiz_cancel_approved_view,
        name="user_cancel_approved",
    ),
    # Staff views
    path("list/", staff.reviews_list_view, name="list"),
    path("<slug:slug>/", staff.reviews_detail_view, name="detail"),
    path("<slug:slug>/approve/", staff.reviews_approve_view, name="approve"),
    path(
        "<slug:slug>/staff_cancel_approve/",
        staff.quiz_cancel_approved_view,
        name="staff_cancel_approved",
    ),
    path(
        "<slug:slug>/reject/",
        staff.reviews_reject_view,
        name="reject",
    ),
    path(
        "<slug:slug>/staff_cancel_reject/",
        staff.quiz_cancel_rejected_view,
        name="staff_cancel_reject",
    ),
]

apps/takes/urls.py
from django.urls import path

from . import views


app_name = "takes"

urlpatterns = [
    path("explore/", views.quiz_explore_view, name="explore"),
    path("results/", views.quiz_user_results_view, name="results"),
    path("tryout/<slug:slug>/", views.quiz_tryout_view, name="tryout"),
    path(
        "tryout/<slug:slug>/results/",
        views.quiz_tryout_results_view,
        name="tryout_results",
    ),
    path("take/<slug:slug>/", views.quiz_take_view, name="take"),
    path(
        "take/<slug:slug>/results/",
        views.quiz_take_results_view,
        name="take_results",
    ),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views import defaults


if not settings.DEBUG:
    from django_otp.admin import OTPAdminSite

    admin.site.__class__ = OTPAdminSite


# Disable unused urls from 3rd party libraries
disabled_urls = [
    path(
        "email/",
        defaults.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    path(
        "inactive/",
        defaults.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
]

urlpatterns = disabled_urls + [
    # Django
    path("admin/", admin.site.urls),
    # 3rd-party
    path("", include("allauth.urls")),
    # Local
    path("", include("apps.pages.urls", namespace="pages")),
    path("", include("apps.users.urls", namespace="users")),
    path("quizzes/", include("apps.quizzes.urls", namespace="quizzes")),
    path("", include("apps.takes.urls", namespace="takes")),
    path("review/", include("apps.reviews.urls", namespace="reviews")),
    path("api/v1/", include("apps.api.urls", namespace="api")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            defaults.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            defaults.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            defaults.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", defaults.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/quizzes/models.py
from unidecode import unidecode

from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string


class Quiz(models.Model):
    """Model representing quizzes"""

    MIN_ITEMS_COUNT = 3
    MAX_ITEMS_COUNT = 15

    class Status(models.IntegerChoices):
        DRAFT = 1  # When initially created
        REVIEW = 2  # When author finishes quiz creation and staff reviews the work
        REJECTED = 3  # If admin/editor reject quiz (comes with RejectedQuizMessage)
        APPROVED = 4  # If admin/editor approves quiz (approved quiz is visible in explore page)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="quizzes"
    )

    title = models.CharField(max_length=65)
    slug = models.SlugField(max_length=130, unique=True)

    description = models.TextField(max_length=255)

    status = models.IntegerField(
        choices=Status.choices,
        default=Status.DRAFT,
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "Quizzes"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Generating unique slug
        if not self.slug:
            slugified_title = slugify(unidecode(self.title))[:30]
            slug = get_random_string(length=4) + "-" + slugified_title

            while Quiz.objects.filter(slug=slug).exists():
                slug = get_random_string(length=4) + "-" + slugified_title

            self.slug = slug
        super().save(*args, **kwargs)

    def get_status_badge_type(self):
        """Get bootstrap color representation based on
        quiz status"""

        if self.status == Quiz.Status.DRAFT:
            return "secondary"
        elif self.status == Quiz.Status.REVIEW:
            return "info"
        elif self.status == Quiz.Status.REJECTED:
            return "danger"
        elif self.status == Quiz.Status.APPROVED:
            return "success"

        raise NotImplementedError(
            "Did you forgot to update get_status_badge_type method?"
        )

    def get_available_item_index(self):
        """Get free index based on quiz items presented"""

        if self.items.all().exists():
            index = self.items.order_by("-index")[0].index + 1
        else:
            index = 1

        return index

    def update_items_indexes(self):
        """Update quiz items indexes in case there might
        be any inconsistency"""

        index = 1

        items = []

        for item in self.items.order_by("index"):
            item.index = index
            items.append(item)
            index += 1

        self.items.bulk_update(items, ["index"])

    def update_results(self) -> None:
        """Create/update/delete related QuizResult objects
        to match the number of items"""

        # If everything is up to date, then number of items
        # should be 1 less than number of results (because they include
        # zero)

        items_count = self.items.count()
        results_count = self.results.count()

        if items_count + 1 > results_count:
            for i in range(results_count, items_count + 1):
                self.results.get_or_create(
                    quiz=self,
                    score=i,
                )
        elif items_count + 1 < results_count:
            for result in self.results.filter(score__gt=items_count):
                result.delete()

    def is_completed_by(self, user):
        """Check if user completed this quiz"""
        return self.completed_quizzes.filter(user=user).exists()


class QuizItem(models.Model):
    """Model representing container for single question-answers item
    in quiz"""

    MIN_ANSWERS = 2
    MAX_ANSWERS = 6
    MIN_CORRECT_ANSWERS = 1
    MAX_CORRECT_ANSWERS = 1

    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name="items",
    )

    question = models.CharField(max_length=65)

    index = models.PositiveIntegerField()

    class Meta:
        ordering = ["index"]

    def __str__(self):
        return f"{self.quiz.title} - {self.index} item"


class QuizItemAnswer(models.Model):
    """Model representing single answer in quizzes item"""

    quiz_item = models.ForeignKey(
        QuizItem,
        on_delete=models.CASCADE,
        related_name="answers",
    )

    text = models.CharField(max_length=65)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quiz_item}'s answer"


class QuizResult(models.Model):
    """Model representing different results of particular quiz,
    based on the number of correct answers by user"""

    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
        related_name="results",
    )

    score = models.PositiveIntegerField()

    text = models.CharField(
        max_length=65,
        # Because QuizResult will be initialized automatically
        blank=True,
    )

apps/quizzes/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response

from apps.quizzes import models
from . import serializers


class QuizApiView(APIView):
    def get(self, request):
        quizzes = models.Quiz.objects.filter(status=models.Quiz.Status.APPROVED)
        serializer = serializers.QuizSerializer(quizzes, many=True)
        return Response(serializer.data)

apps/quizzes/views/details_stricted.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models, forms


@login_required
def quiz_item_view(request, slug, index):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not (request.user == quiz.author or request.user.is_staff):
        raise PermissionDenied

    quiz_item = get_object_or_404(
        models.QuizItem.objects.all(),
        quiz__slug=slug,
        index=index,
    )

    quiz_item_answers = quiz_item.answers.all()

    context = {
        "quiz": quiz,
        "quiz_item": quiz_item,
        "quiz_item_answers": quiz_item_answers,
    }

    return TemplateResponse(request, "quizzes/details_stricted/item.html", context)


@login_required
def quiz_results_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not (request.user == quiz.author or request.user.is_staff):
        raise PermissionDenied

    quiz_results = models.QuizResult.objects.filter(quiz=quiz).order_by("score")

    context = {
        "quiz": quiz,
        "quiz_max_score": quiz.items.count(),
        "quiz_results": quiz_results,
    }

    return TemplateResponse(request, "quizzes/details_stricted/results.html", context)

apps/quizzes/views/quiz.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.db.models.functions import Lower
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models, forms, filters


@login_required
def list_view(request):
    quizzes = (
        models.Quiz.objects.filter(author=request.user)
        .order_by("-created")
        .prefetch_related("items")
        .annotate(completions=Count("completed_quizzes"))
        .annotate(ititle=Lower("title"))
    )

    # Sorting

    current_sort_field = request.GET.get("sort_by")

    if current_sort_field:
        quizzes = quizzes.order_by(current_sort_field)

    # Filtering

    quizzes = filters.QuizListFilter(request.GET, quizzes)

    filter_form = quizzes.form

    # Paginating

    paginator = Paginator(quizzes.qs, 9)

    page = request.GET.get("page")

    try:
        quizzes = paginator.page(page)
    except PageNotAnInteger:
        quizzes = paginator.page(1)
    except EmptyPage:
        quizzes = paginator.page(paginator.num_pages)

    context = {
        "quizzes": quizzes,
        "filter_form": filter_form,
        "current_sort_field": current_sort_field,
    }

    return TemplateResponse(request, "quizzes/quiz/list.html", context)


@login_required
def create_view(request):

    if request.POST:
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect("quizzes:detail", slug=instance.slug)
    else:
        form = forms.QuizForm()

    context = {
        "form": form,
    }

    return TemplateResponse(request, "quizzes/quiz/create.html", context)


@login_required
def detail_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    quiz_items = quiz.items.order_by("index")

    context = {
        "quiz": quiz,
        "quiz_items": quiz_items,
    }

    return TemplateResponse(request, "quizzes/quiz/detail.html", context)


@login_required
def edit_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if quiz.status not in (models.Quiz.Status.DRAFT, models.Quiz.Status.REJECTED):
        raise PermissionDenied

    if request.POST:
        form = forms.QuizForm(request.POST, instance=quiz)

        if form.is_valid():
            instance = form.save()
            return redirect("quizzes:detail", slug=instance.slug)
    else:
        form = forms.QuizForm(instance=quiz)

    context = {"quiz": quiz, "form": form}

    return TemplateResponse(request, "quizzes/quiz/edit.html", context)


@login_required
def delete_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if request.POST:
        form = forms.QuizDeleteForm(request.POST, instance=quiz)

        if form.is_valid():
            quiz.delete()
            return redirect("quizzes:list")
    else:
        form = forms.QuizDeleteForm(instance=quiz)

    context = {"quiz": quiz, "form": form}

    return TemplateResponse(request, "quizzes/quiz/delete.html", context)

apps/quizzes/views/quiz_result.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models, forms


@login_required
def edit_view(request, slug):
    quiz = get_object_or_404(
        models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if quiz.status not in (models.Quiz.Status.DRAFT, models.Quiz.Status.REJECTED):
        raise PermissionDenied

    quiz.update_results()

    QuizResultFormSet = modelformset_factory(
        models.QuizResult,
        fields=("text",),
        labels={"text": "Result"},
        extra=0,
        can_delete=False,
        can_order=False,
    )

    if request.POST:
        quiz_result_formset = QuizResultFormSet(
            request.POST,
            queryset=quiz.results.all(),
        )

        if quiz_result_formset.is_valid():
            quiz_result_formset.save()
            return redirect("quizzes:detail", slug=quiz.slug)
    else:
        quiz_result_formset = QuizResultFormSet(
            queryset=quiz.results.all(),
        )

    context = {
        "quiz": quiz,
        "quiz_result_formset": quiz_result_formset,
        "quiz_max_score": quiz.items.count(),
    }

    return TemplateResponse(request, "quizzes/result/edit.html", context)

templates/quizzes/quiz/create.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}


{% block title %}Create Quiz | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Create Quiz</h2>
            <p>So, you decided to create a quiz? Now we're talkin'!</p>
            <p>But first you have to come up with a title and description</p>
        </div>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex justify-content-center">
                <button class="btn btn-outline-primary" type="submit">Create</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/quizzes/quiz/delete.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}


{% block title %}Delete Quiz | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Delete {{ quiz.title }}</h2>
            <p>Are you sure you want to delete this quiz?</p>
        </div>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex justify-content-center">
                <button class="btn btn-outline-danger" type="submit">Yes</button>
                <a class="btn btn-outline-secondary ms-2" href="{% url 'quizzes:detail' quiz.slug %}">No way</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/quizzes/quiz/detail.html
{% extends '_base.html' %}


{% block title %}{{ quiz.title }} | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-4'>
            {% if quiz.status == quiz.Status.REJECTED %}
                <div class="alert alert-danger mb-3">
                    Reason: {{ quiz.rejected_message.text }}
                </div>
            {% endif %}
            <div class="d-flex justify-content-center align-items-center flex-wrap">
                <!-- This block is needed to center quiz title correctly -->
                <div class="d-inline badge d-inline me-2"></div>
                <h2 class="mb-3">{{ quiz.title }}</h2>
                <div class="ms-2 badge bg-{{ quiz.get_status_badge_type }} bg-gradient mb-2">{{ quiz.get_status_display }}</div>
            </div>
            <p>{{ quiz.description }}</p>
            <div>
                <a class="btn btn-outline-danger m-1" href="{% url 'quizzes:delete' quiz.slug %}">Delete</a>
                <a class="btn btn-outline-info m-1" href="{% url 'takes:tryout' quiz.slug %}">Try it</a>
                {% if quiz.status == quiz.Status.DRAFT %}
                    <a class="btn btn-outline-info m-1" href="{% url 'quizzes:edit' quiz.slug %}">Edit</a>
                    <a class="btn btn-outline-info m-1" href="{% url 'quizzes:results_edit' quiz.slug %}">Results</a>
                    <a class="btn btn-outline-success m-1" href="{% url 'reviews:submit' quiz.slug %}">Submit</a>
                {% elif quiz.status == quiz.Status.REVIEW %}
                    <a class="btn btn-outline-info m-1" href="{% url 'quizzes:stricted_results' quiz.slug %}">Results</a>
                    <a class="btn btn-outline-warning m-1" href="{% url 'reviews:cancel_review' quiz.slug %}">Cancel</a>
                {% elif quiz.status == quiz.Status.REJECTED %}
                    <a class="btn btn-outline-info m-1" href="{% url 'quizzes:edit' quiz.slug %}">Edit</a>
                    <a class="btn btn-outline-info m-1" href="{% url 'quizzes:results_edit' quiz.slug %}">Results</a>
                    <a class="btn btn-outline-success m-1" href="{% url 'reviews:submit' quiz.slug %}">Submit</a>
                {% elif quiz.status == quiz.Status.APPROVED %}
                    <a class="btn btn-outline-info m-1" href="{% url 'quizzes:stricted_results' quiz.slug %}">Results</a>
                    <a class="btn btn-outline-warning m-1" href="{% url 'reviews:user_cancel_approved' quiz.slug %}">Cancel</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="col-xl-6 offset-xl-3">
    <div class="list-group text-center">
        {% for quiz_item in quiz_items %}
            {% if quiz.status == quiz.Status.DRAFT or quiz.status == quiz.Status.REJECTED %}
                <a href="{% url 'quizzes:item_edit' quiz.slug quiz_item.index %}" class="list-group-item list-group-item-action mb-2 shadow-sm">
                    {{quiz_item.index}}. {{ quiz_item.question }}
                </a>
            {% elif quiz.status == quiz.Status.REVIEW or quiz.status == quiz.Status.APPROVED %}
                <a href="{% url 'quizzes:stricted_item' quiz.slug quiz_item.index %}" class="list-group-item list-group-item-action mb-2 shadow-sm">
                    {{quiz_item.index}}. {{ quiz_item.question }}
                </a>
            {% endif %}

        {% empty %}
            <p>Looks empty, isn't it? Consider adding something</p>

        {% endfor %}
    </div>
    {% if quiz.status == quiz.Status.DRAFT or quiz.status == quiz.Status.REJECTED %}
        {% if quiz.items.count < quiz.MAX_ITEMS_COUNT %}
            <div class="d-flex justify-content-center mt-2">
                <a class="btn btn-outline-success" href="{% url 'quizzes:item_create' quiz.slug %}">Add Item</a>
            </div>
        {% endif %}
    {% endif %}
</div>
{% endblock content %}

templates/quizzes/quiz/edit.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}


{% block title %}Edit Poll | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Edit {{ quiz.title }}</h2>
        </div>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex justify-content-center">
                <button class="btn btn-outline-success mx-1" type="submit">Save</button>
                <a class="btn btn-outline-secondary mx-1" href="{% url 'quizzes:detail' quiz.slug %}">Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/quizzes/quiz/list.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load sorting_tags %}
{% load param_replace %}


{% block title %}Quizzes List | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Quizzes List</h2>
            <p>Here's what you have created so far</p>
            <a class="btn btn-outline-success mt-2 mb-3" href="{% url 'quizzes:create' %}">Create</a>
            <div class="fs-5" style="color: #9c9c9c;">
                {% sort_link "Title" "ititle" %}
                &middot;
                {% sort_link "Created" "created" %}
                &middot;
                {% sort_link "Completions" "completions" %}
            </div>
        </div>
        <form method="get" class="mb-4 offset-xl-4 col-xl-4" id="filter_form">
            {{ filter_form|crispy }}
        </form>
    </div>
</div>
<div class="row gx-5">
    {% for quiz in quizzes %}
    <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-1">
            <div class="card-body p-4">
                <div class="badge bg-{{ quiz.get_status_badge_type }} bg-gradient mb-2">{{ quiz.get_status_display }}</div>
                <a class="text-decoration-none link-dark stretched-link" href="{% url 'quizzes:detail' quiz.slug %}"><h5 class="card-title mb-3">{{ quiz.title }}</h5></a>
                <p class="card-text mb-0">{{ quiz.description }}</p>
            </div>
            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                <div class="d-flex align-items-end justify-content-between">
                    <div class="d-flex align-items-center">
                        <div class="small">
                            <div class="fw-bold">{{ quiz.author.username }}</div>
                            <div class="text-muted">{{ quiz.items.count }} questions &middot; {{ quiz.completions }} completions</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
        <p class="text-center">Nothing here just yet...</p>
    {% endfor %}

    <div class="d-flex mt-2 justify-content-center text-center">
        <span class="step-links">
            <span class="current">
                Page {{ quizzes.number }} of {{ quizzes.paginator.num_pages }}
            </span><br>

            {% if quizzes.has_previous %}
                <a href="?{% param_replace page=quizzes.previous_page_number %}" class="mt-2 btn btn-outline-secondary pagination-btn" style="width: 90px;">Previous</a>
            {% endif %}

            {% if quizzes.has_next %}
                <a href="?{% param_replace page=quizzes.next_page_number %}" class="mt-2 btn btn-outline-secondary pagination-btn">Next</a>
            {% endif %}
        </span>
    </div>

</div>
{% endblock content %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_status').bind('change', function(event) {
            $('#filter_form').trigger("submit");
        });
    });
</script>
{% endblock js %}