apps/quizzes/urls.py
from django.urls import path

from .views import (
    quiz,
    quiz_item,
    quiz_result,
    details_stricted,
)


app_name = "quizzes"

urlpatterns = [
    # Quiz views
    # Since quiz's slugs have 4 random characters followed
    # by dash, there won't be any overlap with this urls
    path("list/", quiz.list_view, name="list"),
    path("create/", quiz.create_view, name="create"),
    path("<slug:slug>/", quiz.detail_view, name="detail"),
    path("<slug:slug>/edit/", quiz.edit_view, name="edit"),
    path("<slug:slug>/delete/", quiz.delete_view, name="delete"),
    # QuizItem views
    path(
        "<slug:slug>/item/create/",
        quiz_item.create_view,
        name="item_create",
    ),
    path(
        "<slug:slug>/item/<int:index>/",
        quiz_item.edit_view,
        name="item_edit",
    ),
    path(
        "<slug:slug>/item/<int:index>/delete/",
        quiz_item.delete_view,
        name="item_delete",
    ),
    # QuizResult views
    path(
        "<slug:slug>/results/",
        quiz_result.edit_view,
        name="results_edit",
    ),
    # Details stricted views
    path(
        "<slug:slug>/item/<int:index>/stricted/",
        details_stricted.quiz_item_view,
        name="stricted_item",
    ),
    path(
        "<slug:slug>/results/stricted/",
        details_stricted.quiz_results_view,
        name="stricted_results",
    ),
]

apps/reviews/urls.py
from django.urls import path

from .views import user, staff


app_name = "reviews"

urlpatterns = [
    # User views
    path("<slug:slug>/submit/", user.quiz_submit_for_review_view, name="submit"),
    path(
        "<slug:slug>/cancel_review/",
        user.quiz_cancel_review_view,
        name="cancel_review",
    ),
    path(
        "<slug:slug>/cancel_approve/",
        user.quiz_cancel_approved_view,
        name="user_cancel_approved",
    ),
    # Staff views
    path("list/", staff.reviews_list_view, name="list"),
    path("<slug:slug>/", staff.reviews_detail_view, name="detail"),
    path("<slug:slug>/approve/", staff.reviews_approve_view, name="approve"),
    path(
        "<slug:slug>/staff_cancel_approve/",
        staff.quiz_cancel_approved_view,
        name="staff_cancel_approved",
    ),
    path(
        "<slug:slug>/reject/",
        staff.reviews_reject_view,
        name="reject",
    ),
    path(
        "<slug:slug>/staff_cancel_reject/",
        staff.quiz_cancel_rejected_view,
        name="staff_cancel_reject",
    ),
]

apps/takes/urls.py
from django.urls import path

from . import views


app_name = "takes"

urlpatterns = [
    path("explore/", views.quiz_explore_view, name="explore"),
    path("results/", views.quiz_user_results_view, name="results"),
    path("tryout/<slug:slug>/", views.quiz_tryout_view, name="tryout"),
    path(
        "tryout/<slug:slug>/results/",
        views.quiz_tryout_results_view,
        name="tryout_results",
    ),
    path("take/<slug:slug>/", views.quiz_take_view, name="take"),
    path(
        "take/<slug:slug>/results/",
        views.quiz_take_results_view,
        name="take_results",
    ),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views import defaults


if not settings.DEBUG:
    from django_otp.admin import OTPAdminSite

    admin.site.__class__ = OTPAdminSite


# Disable unused urls from 3rd party libraries
disabled_urls = [
    path(
        "email/",
        defaults.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    path(
        "inactive/",
        defaults.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
]

urlpatterns = disabled_urls + [
    # Django
    path("admin/", admin.site.urls),
    # 3rd-party
    path("", include("allauth.urls")),
    # Local
    path("", include("apps.pages.urls", namespace="pages")),
    path("", include("apps.users.urls", namespace="users")),
    path("quizzes/", include("apps.quizzes.urls", namespace="quizzes")),
    path("", include("apps.takes.urls", namespace="takes")),
    path("review/", include("apps.reviews.urls", namespace="reviews")),
    path("api/v1/", include("apps.api.urls", namespace="api")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            defaults.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            defaults.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            defaults.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", defaults.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

apps/polls/models.py
from unidecode import unidecode

from django.conf import settings
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string


class Poll(models.Model):
    """Model representing polls"""

    class Status(models.IntegerChoices):
        DRAFT = 1  # When initially created
        WAITING_FOR_REVIEW = 2  # When author finishes poll creation
        REJECTED = 3  # If admin/editor reject poll (comes with RejectedPollMessage)
        APPROVED = 4  # If admin/editor approves poll (approved poll will be published)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="polls"
    )

    title = models.CharField(max_length=65)
    slug = models.SlugField(max_length=130, unique=True)

    description = models.TextField(max_length=255)

    # If True, other users will see the poll
    published = models.BooleanField(default=False)

    status = models.IntegerField(
        choices=Status.choices,
        default=Status.DRAFT,
    )

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # Generating unique slug
        slugified_title = slugify(unidecode(self.title))
        slug = get_random_string(length=4) + "-" + slugified_title

        while Poll.objects.filter(slug=slug).exists():
            slug = get_random_string(length=4) + "-" + slugified_title

        self.slug = slug
        super().save(*args, **kwargs)

    def get_status_badge_type(self):
        if self.status == Poll.Status.DRAFT:
            return "secondary"
        elif self.status == Poll.Status.WAITING_FOR_REVIEW:
            return "info"
        elif self.status == Poll.Status.REJECTED:
            return "danger"
        elif self.status == Poll.Status.APPROVED:
            return "success"

        raise NotImplementedError(
            "Did you forgot to update get_status_badge_type method?"
        )

    def get_available_index(self):
        index = 1

        while self.items.filter(index=index).exists():
            index += 1

        return index


class PollItem(models.Model):
    """Model representing container for single question-answers item
    in poll"""

    MIN_ANSWERS = 2
    MAX_ANSWERS = 6
    MIN_CORRECT_ANSWERS = 1
    MAX_CORRECT_ANSWERS = 1

    poll = models.ForeignKey(
        Poll,
        on_delete=models.CASCADE,
        related_name="items",
    )

    question = models.CharField(max_length=65)

    index = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.poll.title} - {self.index} item"


class PollItemAnswer(models.Model):
    """Model representing single answer in poll's item"""

    poll_item = models.ForeignKey(
        PollItem,
        on_delete=models.CASCADE,
        related_name="answers",
    )

    text = models.CharField(max_length=65)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.poll_item}'s answer"

apps/reviews/forms.py
from django import forms

from . import models


class QuizRejectedMessageForm(forms.ModelForm):
    text = forms.CharField(
        min_length=3,
        max_length=255,
        widget=forms.Textarea,
        label="Message",
    )

    class Meta:
        model = models.QuizRejectedMessage
        fields = ("text",)

apps/reviews/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models as quizzes_models

from . import verificators


@login_required
def quiz_submit_for_review_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    if not request.user.is_email_verified():
        messages.error(request, "You can't submit quiz with unverified e-mail.")
        return redirect("quizzes:detail", slug=quiz.slug)

    suitable, message = verificators.is_quiz_suitable_for_submission(quiz)

    if not suitable:
        messages.error(request, message)
        return redirect("quizzes:detail", slug=quiz.slug)

    quiz.status = quiz.Status.REVIEW
    quiz.save()

    messages.success(request, message)

    return redirect("quizzes:detail", slug=quiz.slug)


@login_required
def quiz_cancel_review_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    suitable, message = verificators.is_quiz_suitable_for_review_cancel(quiz)

    if not suitable:
        messages.error(request, message)
        return redirect("quizzes:detail", slug=quiz.slug)

    quiz.status = quiz.Status.DRAFT
    quiz.save()

    messages.success(request, message)

    return redirect("quizzes:detail", slug=quiz.slug)


@login_required
def quiz_cancel_approved_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    suitable, message = verificators.is_quiz_suitable_for_approved_cancel(quiz)

    if not suitable:
        messages.error(request, message)
        return redirect("quizzes:detail", slug=quiz.slug)

    if request.POST:
        quiz.status = quizzes_models.Quiz.Status.DRAFT
        quiz.published = False
        quiz.save()
        return redirect("quizzes:detail", slug=quiz.slug)

    context = {
        "quiz": quiz,
    }

    return TemplateResponse(request, "reviews/cancel_approved.html", context)


def quiz_staff_cancel_approved_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    suitable, message = verificators.is_quiz_suitable_for_approved_cancel(quiz)

    if not suitable:
        messages.error(request, message)
        return redirect("reviews:detail", slug=quiz.slug)

    if request.POST:
        quiz.status = quizzes_models.Quiz.Status.REVIEW
        quiz.published = False
        quiz.save()
        return redirect("reviews:detail", slug=quiz.slug)

    context = {
        "quiz": quiz,
    }

    return TemplateResponse(request, "reviews/staff_cancel_approved.html", context)


@login_required
def reviews_list_view(request):

    if not request.user.is_staff:
        raise PermissionDenied

    quizzes = (
        quizzes_models.Quiz.objects.exclude(status=quizzes_models.Quiz.Status.DRAFT)
        .order_by("-created")
        .prefetch_related("items")
    )

    context = {
        "quizzes": quizzes,
    }

    return TemplateResponse(request, "reviews/list.html", context)


def reviews_detail_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.exclude(status=quizzes_models.Quiz.Status.DRAFT),
        slug=slug,
    )

    if not request.user.is_staff:
        raise PermissionDenied

    quiz_items = quiz.items.order_by("index")

    context = {
        "quiz": quiz,
        "quiz_items": quiz_items,
    }

    return TemplateResponse(request, "reviews/detail.html", context)


@login_required
def reviews_approve_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.filter(status=quizzes_models.Quiz.Status.REVIEW),
        slug=slug,
    )

    if not request.user.is_staff:
        raise PermissionDenied

    if request.POST:
        quiz.status = quizzes_models.Quiz.Status.APPROVED
        quiz.published = True
        quiz.save()
        return redirect("reviews:list")

    context = {
        "quiz": quiz,
    }

    return TemplateResponse(request, "reviews/approve.html", context)


@login_required
def reviews_reject_view(request, slug):
    pass

apps/reviews/views/staff.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse

from apps.quizzes import models as quizzes_models
from apps.reviews import verificators, forms, models, filters


@login_required
def reviews_list_view(request):

    if not request.user.is_staff:
        raise PermissionDenied

    quizzes = (
        quizzes_models.Quiz.objects.exclude(status=quizzes_models.Quiz.Status.DRAFT)
        .order_by("-created")
        .prefetch_related("items")
        .annotate(completions=Count("completed_quizzes"))
    )

    current_sort_field = request.GET.get("sort_by")

    if current_sort_field:
        quizzes = quizzes.order_by(current_sort_field)

    quizzes = filters.QuizReviewFilter(request.GET, quizzes)

    filter_form = quizzes.form

    paginator = Paginator(quizzes.qs, 9)

    page = request.GET.get("page")

    try:
        quizzes = paginator.page(page)
    except PageNotAnInteger:
        quizzes = paginator.page(1)
    except EmptyPage:
        quizzes = paginator.page(paginator.num_pages)

    context = {
        "quizzes": quizzes,
        "filter_form": filter_form,
        "current_sort_field": current_sort_field,
    }

    return TemplateResponse(request, "reviews/staff/list.html", context)


@login_required
def reviews_detail_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.exclude(status=quizzes_models.Quiz.Status.DRAFT),
        slug=slug,
    )

    if not request.user.is_staff:
        raise PermissionDenied

    quiz_items = quiz.items.order_by("index")

    context = {
        "quiz": quiz,
        "quiz_items": quiz_items,
    }

    return TemplateResponse(request, "reviews/staff/detail.html", context)


@login_required
def reviews_approve_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.filter(status=quizzes_models.Quiz.Status.REVIEW),
        slug=slug,
    )

    if not request.user.is_staff:
        raise PermissionDenied

    if request.POST:
        quiz.status = quizzes_models.Quiz.Status.APPROVED
        quiz.save()
        return redirect("reviews:list")

    context = {
        "quiz": quiz,
    }

    return TemplateResponse(request, "reviews/staff/approve.html", context)


@login_required
def quiz_cancel_approved_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    suitable, message = verificators.is_quiz_suitable_for_approved_cancel(quiz)

    if not suitable:
        messages.error(request, message)
        return redirect("reviews:detail", slug=quiz.slug)

    if request.POST:
        quiz.status = quizzes_models.Quiz.Status.REVIEW
        quiz.save()
        return redirect("reviews:detail", slug=quiz.slug)

    context = {
        "quiz": quiz,
    }

    return TemplateResponse(request, "reviews/staff/cancel_approved.html", context)


@login_required
def reviews_reject_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.filter(status=quizzes_models.Quiz.Status.REVIEW),
        slug=slug,
    )

    if not request.user.is_staff:
        raise PermissionDenied

    if request.POST:
        form = forms.QuizRejectedMessageForm(request.POST)

        if form.is_valid():
            models.QuizRejectedMessage.objects.filter(quiz=quiz).delete()
            instance = form.save(commit=False)
            instance.quiz = quiz
            instance.save()
            quiz.status = quizzes_models.Quiz.Status.REJECTED
            quiz.save()
            return redirect("reviews:list")

    else:
        form = forms.QuizRejectedMessageForm()

    context = {
        "quiz": quiz,
        "form": form,
    }

    return TemplateResponse(request, "reviews/staff/reject.html", context)


@login_required
def quiz_cancel_rejected_view(request, slug):
    quiz = get_object_or_404(
        quizzes_models.Quiz.objects.all(),
        slug=slug,
    )

    if not request.user == quiz.author:
        raise PermissionDenied

    suitable, message = verificators.is_quiz_suitable_for_rejected_cancel(quiz)

    if not suitable:
        messages.error(request, message)
        return redirect("reviews:detail", slug=quiz.slug)

    quiz.status = quizzes_models.Quiz.Status.REVIEW
    quiz.save()

    return redirect("reviews:detail", slug=quiz.slug)

templates/reviews/staff/approve.html
{% extends '_base.html' %}


{% block title %}Approve Quiz | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Approve {{ quiz.title }}</h2>
            <p>Are you sure you want to approve this quiz?</p>
        </div>
        <form method="post">{% csrf_token %}
            <div class="d-flex justify-content-center">
                <button class="btn btn-outline-success" type="submit">Yes</button>
                <a class="btn btn-outline-secondary ms-2" href="{% url 'reviews:detail' quiz.slug %}">No way</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/reviews/staff/cancel_approved.html
{% extends '_base.html' %}


{% block title %}Cancel approve | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Cancel approve {{ quiz.title }}</h2>
            <p>Are you sure you want to cancel approve on this quiz?</p>
            <p>All of its statistics will be forever lost</p>
        </div>
        <form method="post">{% csrf_token %}
            <div class="d-flex justify-content-center">
                <button class="btn btn-outline-danger" type="submit">Yes</button>
                <a class="btn btn-outline-secondary ms-2" href="{% url 'reviews:detail' quiz.slug %}">No way</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/reviews/staff/detail.html
{% extends '_base.html' %}


{% block title %}{{ quiz.title }} Review | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-4'>
            <div class="d-flex justify-content-center align-items-center flex-wrap">
                <!-- This block is needed to center quiz title correctly -->
                <div class="d-inline badge d-inline me-2"></div>
                <h2 class="mb-3">{{ quiz.title }}</h2>
                <div class="ms-2 badge bg-{{ quiz.get_status_badge_type }} bg-gradient mb-2">{{ quiz.get_status_display }}</div>
            </div>
            <p>{{ quiz.description }}</p>
            <div>
                <a class="btn btn-outline-info m-1" href="{% url 'takes:tryout' quiz.slug %}">Try it</a>
                <a class="btn btn-outline-info m-1" href="{% url 'quizzes:stricted_results' quiz.slug %}">Results</a>
                {% if quiz.status == quiz.Status.REVIEW %}
                    <a class="btn btn-outline-danger m-1" href="{% url 'reviews:reject' quiz.slug %}">Reject</a>
                    <a class="btn btn-outline-success m-1" href="{% url 'reviews:approve' quiz.slug %}">Approve</a>
                {% elif quiz.status == quiz.Status.APPROVED %}
                    <a class="btn btn-outline-warning m-1" href="{% url 'reviews:staff_cancel_approved' quiz.slug %}">Cancel</a>
                {% elif quiz.status == quiz.Status.REJECTED %}
                    <a class="btn btn-outline-warning m-1" href="{% url 'reviews:staff_cancel_reject' quiz.slug %}">Cancel</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="col-xl-6 offset-xl-3">
    <div class="list-group text-center">
        {% for quiz_item in quiz_items %}
            <a href="{% url 'quizzes:stricted_item' quiz.slug quiz_item.index %}" class="list-group-item list-group-item-action mb-2 shadow-sm">
                {{quiz_item.index}}. {{ quiz_item.question }}
            </a>
        {% empty %}
        <p>Looks empty, isn't it? Consider adding something</p>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/reviews/staff/list.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% load sorting_tags %}
{% load param_replace %}


{% block title %}Reviews List | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Reviews List</h2>
            <div class="fs-5" style="color: #9c9c9c;">
                {% sort_link "Title" "title" %}
                &middot;
                {% sort_link "Created" "created" %}
                &middot;
                {% sort_link "Completions" "completions" %}
            </div>
        </div>
        <form method="get" class="mb-4 offset-xl-4 col-xl-4" id="filter_form">
            {{ filter_form|crispy }}
        </form>
    </div>
</div>
<div class="row gx-5">
    {% for quiz in quizzes %}
    <div class="col-lg-4 mb-5">
        <div class="card h-100 shadow border-1">
            <div class="card-body p-4">
                <div class="badge bg-{{ quiz.get_status_badge_type }} bg-gradient mb-2">{{ quiz.get_status_display }}</div>
                <a class="text-decoration-none link-dark stretched-link" href="{% url 'reviews:detail' quiz.slug %}"><h5 class="card-title mb-3">{{ quiz.title }}</h5></a>
                <p class="card-text mb-0">{{ quiz.description }}</p>
            </div>
            <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
                <div class="d-flex align-items-end justify-content-between">
                    <div class="d-flex align-items-center">
                        <div class="small">
                            <div class="fw-bold">{{ quiz.author.username }}</div>
                            <div class="text-muted">{{ quiz.items.count }} questions &middot; {{ quiz.completions }} completions</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% empty %}
        <p class="text-center">Nothing here just yet...</p>
    {% endfor %}

    <div class="d-flex mt-2 justify-content-center text-center">
        <span class="step-links">
            <span class="current">
                Page {{ quizzes.number }} of {{ quizzes.paginator.num_pages }}
            </span><br>

            {% if quizzes.has_previous %}
                <a href="?{% param_replace page=quizzes.previous_page_number %}" class="mt-2 btn btn-outline-secondary pagination-btn">Previous</a>
            {% endif %}

            {% if quizzes.has_next %}
                <a href="?{% param_replace page=quizzes.next_page_number %}" class="mt-2 btn btn-outline-secondary pagination-btn">Next</a>
            {% endif %}
        </span>
    </div>

</div>
{% endblock content %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function() {
        $('#id_status').bind('change', function(event) {
            $('#filter_form').trigger("submit");
        });
    });
</script>
{% endblock js %}

templates/reviews/staff/reject.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}


{% block title %}Reject Quiz | DQA{% endblock title %}

{% block content %}
<div class="row gx-5 justify-content-center">
    <div class="col-lg-8 col-xl-6">
        <div class='text-center mb-3'>
            <h2 class="mb-3">Reject {{ quiz.title }}</h2>
            <p>Are you sure you want to reject this quiz?</p>
        </div>
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <div class="d-flex justify-content-center">
                <button class="btn btn-outline-danger" type="submit">Yes</button>
                <a class="btn btn-outline-secondary ms-2" href="{% url 'reviews:detail' quiz.slug %}">No way</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}