apps/api/urls.py
from django.urls import path, include

from apps.takes.api import views as takes_views

app_name = "api"

urlpatterns = [
    path("auth/", include("dj_rest_auth.urls")),
    path("auth/signup/", include("dj_rest_auth.registration.urls")),
    path("explore/", takes_views.ExploreApiView.as_view(), name="explore"),
    path("take/<slug:slug>/", takes_views.QuizTakeApiView.as_view(), name="take"),
    path("results/", takes_views.QuizTakeResultsApiView.as_view(), name="results"),
]

apps/pages/urls.py
from django.urls import path

from django.views.generic import TemplateView


app_name = "pages"

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
]

apps/quizzes/urls.py
from django.urls import path

from .views import (
    quiz,
    quiz_item,
    quiz_result,
    details_stricted,
)


app_name = "quizzes"

urlpatterns = [
    # Quiz views
    # Since quiz's slugs have 4 random characters followed
    # by dash, there won't be any overlap with this urls
    path("list/", quiz.list_view, name="list"),
    path("create/", quiz.create_view, name="create"),
    path("<slug:slug>/", quiz.detail_view, name="detail"),
    path("<slug:slug>/edit/", quiz.edit_view, name="edit"),
    path("<slug:slug>/delete/", quiz.delete_view, name="delete"),
    # QuizItem views
    path(
        "<slug:slug>/item/create/",
        quiz_item.create_view,
        name="item_create",
    ),
    path(
        "<slug:slug>/item/<int:index>/",
        quiz_item.edit_view,
        name="item_edit",
    ),
    path(
        "<slug:slug>/item/<int:index>/delete/",
        quiz_item.delete_view,
        name="item_delete",
    ),
    # QuizResult views
    path(
        "<slug:slug>/results/",
        quiz_result.edit_view,
        name="results_edit",
    ),
    # Details stricted views
    path(
        "<slug:slug>/item/<int:index>/stricted/",
        details_stricted.quiz_item_view,
        name="stricted_item",
    ),
    path(
        "<slug:slug>/results/stricted/",
        details_stricted.quiz_results_view,
        name="stricted_results",
    ),
]

apps/users/urls.py
from django.urls import path

from . import views


app_name = "users"

urlpatterns = [
    path("profile/", views.user_profile_view, name="profile"),
    path(
        "resend_verification_email/",
        views.resend_verification_email_view,
        name="resend_verification_email",
    ),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.views import defaults


if not settings.DEBUG:
    from django_otp.admin import OTPAdminSite

    admin.site.__class__ = OTPAdminSite


# Disable unused urls from 3rd party libraries
disabled_urls = [
    path(
        "email/",
        defaults.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
    path(
        "inactive/",
        defaults.page_not_found,
        kwargs={"exception": Exception("Page not Found")},
    ),
]

urlpatterns = disabled_urls + [
    # Django
    path("admin/", admin.site.urls),
    # 3rd-party
    path("", include("allauth.urls")),
    # Local
    path("", include("apps.pages.urls", namespace="pages")),
    path("", include("apps.users.urls", namespace="users")),
    path("quizzes/", include("apps.quizzes.urls", namespace="quizzes")),
    path("", include("apps.takes.urls", namespace="takes")),
    path("review/", include("apps.reviews.urls", namespace="reviews")),
    path("api/v1/", include("apps.api.urls", namespace="api")),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            defaults.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            defaults.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            defaults.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", defaults.server_error),
    ]

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

templates/_base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <title>{% block title %}Django Quiz App{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'base/css/core.css' %}" rel="stylesheet" />
        <!-- Dropdown CSS -->
        <link href="{% static 'base/css/dropdown.css' %}" rel="stylesheet" />
        {% block css %}
        {% endblock css %}
    </head>
    <body class="d-flex flex-column h-100">
        <main class="flex-shrink-0">
            <!-- Navigation-->
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <div class="container px-5">
                    <a class="navbar-brand" href="{% url 'pages:home' %}">Django Quiz App</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                            <li class="nav-item mx-1"><a class="nav-link" href="{% url 'pages:home' %}">Home</a></li>
                            <li class="nav-item mx-1"><a class="nav-link" href="{% url 'takes:explore' %}">Explore</a></li>
                            <li class="nav-item mx-1"><a class="nav-link" href="{% url 'takes:results' %}">Results</a></li>
                            {% if request.user.is_staff %}
                                <li class="nav-item mx-1"><a class="nav-link" href="{% url 'reviews:list' %}">Review</a></li>
                            {% endif %}
                            <li class="nav-item dropdown mx-1">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Quizzes</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                    <li><a class="dropdown-item" href="{% url 'quizzes:list' %}">List</a></li>
                                    <li><a class="dropdown-item" href="{% url 'quizzes:create' %}">Create</a></li>
                                </ul>
                            </li>
                            {% if request.user.is_authenticated %}
                            <li class="nav-item dropdown rounded border mx-1">
                                <a class="nav-link dropdown-toggle" id="navbarDropdownBlog" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">{{ request.user.username }}</a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownBlog">
                                    <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>
                                    <li><a class="dropdown-item" href="{% url 'account_logout' %}">Log out</a></li>
                                </ul>
                            </li>
                            {% else %}
                            <li class="nav-item mx-1"><a class="nav-link" href="{% url 'account_login' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Messages (Adapted from django-bootstrap-v5) -->
            {% autoescape off %}
                {% for message in messages %}
                    {% if message.tags == 'error'%}
                        <div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
                            <!-- This block is needed to center message text correctly -->
                            <div class="btn d-inline" style="padding-right: 34px;"></div>

                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                            {{ message }}
                        </div>
                    {% else %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show text-center" role="alert">
                            <!-- This block is needed to center message text correctly -->
                            <div class="btn d-inline" style="padding-right: 34px;"></div>

                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="close"></button>
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
            {% endautoescape %}
            <!-- Content section-->
            <section class="py-5">
                <div class="container px-5 my-5">
                    {% block content %}
                    {% endblock content %}
                </div>
            </section>
        </main>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'base/js/script.js'%}"></script>
        <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        {% block js %}
        {% endblock js %}
    </body>
</html>